language: python
python:
  - "3.5"
sudo: false
install:
  - "source ./travisci_setup.sh"
before_script:
  - pip install codecov
script:
  - "coverage run -m unittest discover -s saffrontree/tests/ -p '*_test.py'"
after_success:
  - codecov